### PR TITLE
Implemented yamashi/SkyrimOnline#12 , yamashi/SkyrimOnline#20 , yamashi/SkyrimOnline#53.

### PR DESCRIPTION
**Pull request by WopsS**
Implemented issue yamashi/SkyrimOnline#12 , issue yamashi/SkyrimOnline#20 , issue yamashi/SkyrimOnline#53.

### CODE REVIEW

**Comment by WopsS** [comment]
Chat design is now flat and some other changes.
Chat will keep now 200 messages.

**Comment by WopsS** [comment]
Do you merge this pull request?

**Comment by tomtinsley99** [comment]
Do you guys have any idea of the next release of this mod?

**Comment by WopsS** [comment]
Hello @tomtinsley99 Yamashi should known this.

**Pull request merged**
